ca_urls = ["https://127.0.0.1:3000"]
ca_certs = ['''
-----BEGIN CERTIFICATE-----
MIIE4jCCAsqgAwIBAgIUAwAAAAAAAAAAAAAAAAAAAAAAAAAwDQYJKoZIhvcNAQEL
BQAwFjEUMBIGA1UEAwwLdGVzdCBzZXJ2ZXIwHhcNMjUwNzExMTUzMjA1WhcNMjkw
ODE5MTUzMjA1WjAXMRUwEwYDVQQDDAxIVFRQUyBTZXJ2ZXIwggIiMA0GCSqGSIb3
DQEBAQUAA4ICDwAwggIKAoICAQDTSVq5xmp+pW9KWaPy/f+F+kGGmNU+GSJ3lgNJ
u6eV//WauWn5ycd3AjMbHTqMIbfe4F/jjzdUsIMJwUXdmdr6rCKw9wZ1c19AiRMZ
hLLEkNA/ImDAz3HBc5ibtS2m5n1S6dWY6eq0YNFLhZB5lI0E8xNjlYorZWM6M7sy
PBzlQColBymgtWYgf8128oOOp5ZjlldSvyymfR9p43ILY2I87OEHWfSaHiZfPYzY
VCDrkReW17rIuZPnLJX4EGFMeiHsXW4G0Tjjxubeqdy8OW0spJAJ6FsRnStBTWtI
4RBFnx/9/oP21CF9CvpyKh24y+UmKoZTJ9hqcoVN34rAkVCwlpaEyUZvyMnT0INh
OemPDn4WGq5VRIpQCtRGXbKADK3/kw+1du4LHZv8pPBASrL78y9lRvKz+CUheDCQ
5nG6+v4plBY0Fi+DtDqg9gCmleD9GW+9Y8YYTVcIaCPsCY/wTICpYjsuV0bsVxNS
DhaADXmCS9TelneolQrg79jg8irYpoeclU0oL1lwEjOLB7mgEvf985BlG7Kz95ib
1UcPPOoD8wSXjc/X5JNicq1ldgvlRoMTn7tRim3OXnJFBGN7dkvSoQDsoyxfgbOc
tcCucGmqZ7th+Iv5SnQhcIH/QQ5XCwcsFBYwqvxfq9L70S8aZSyopDzL7m3ZGsct
Q08yYQIDAQABoycwJTATBgNVHSUEDDAKBggrBgEFBQcDATAOBggrBgEFBQcBAQQC
MAAwDQYJKoZIhvcNAQELBQADggIBAJjyPLH8r4GUw/3w3S9P5UQXN+kMg65SuVwN
YL6CGB0hDkkrMo6kbyzNcHAdGoRNp3+APCpNbGdyQYMabiqglOgHcG2y/9gyDk6o
/qfaaeNh8teuCY9cDJlHS8y/v2vqoqneVX+Ey+XdQkmUrjeNJ1bwKqNHPjHwsJp5
+lZCLpexj0w9z3cnjpBnp+3PE1sm7+BXXx5dJHiuxPEkH38rGsbw66hzn+Kkd24c
tnNZEU5N8+bLbFkgayth/5rmkQwkPp4wd0uQSe9bOQP9gZTPXPpyyRjzYKYi3WJ9
V0d+8jxm18d+5deQA5LNeM1mKnLs7uMkT416qww20AGG7tORmC5Ga8rBJ6jkghtk
zr/snX7PZgRvM/b/D708BVD68DWuqf21txq2MSOwA8imnYlmLQwAQJXWJe6994Cs
VMQAOjFdx+W7/4Wi/Zm67I5zgnx/jP777p0kKQGtzcrhN0KbYvvyWlEJTNBSMb7E
KEZq7p5cHlK5z0ZnJNlVcBNHM+7RewU7v/FxRWaejEbrw4H4/30IvcW9gL1aHAPX
8qQoh8+7e7y855/BmGZpLYFBQHc5+UVZYN6nKjxbG1sz/fpR3m70y8tKVHw9jcnV
e/ZDksX0LuARJbgUVlZPP4xiEiBk4sxJp3V+cHhAG9Hjg2ZbMu8Rob2k7KAWA1fl
JdEZ0iAE
-----END CERTIFICATE-----
''',
'''
-----BEGIN CERTIFICATE-----
MIIE7zCCAtegAwIBAgIUSPAcSVrV0KkfEQoW/s3k7z60eHMwDQYJKoZIhvcNAQEL
BQAwFjEUMBIGA1UEAwwLdGVzdCBzZXJ2ZXIwHhcNMjUwNzExMTUzMTE2WhcNMjkw
ODE5MTUzMTE2WjAWMRQwEgYDVQQDDAt0ZXN0IHNlcnZlcjCCAiIwDQYJKoZIhvcN
AQEBBQADggIPADCCAgoCggIBALuJYb1llAPhuZS8FA5zjYzpWQRZ6SR6KHIYcDiJ
78BKgFgzX8elNkGmv45dY7ogPaxccX+lRP7Skxwx+D6Oh9OeXmhn/M+sGJU61HQt
VwBcq/qnrBRPxWXfjJ0Ya9M5GJfxvFSPhVxuaTowXRmi/Pwip/HLEPIqNPJqqWOO
wJYfmX3rNg9DGNpq7GfW78pBwJm0Qeh1nm76wQNtY8ChtYjORQ0ULMyqudvN4G+b
+nwRp98Zppl8iPsFHLi+nbxgoBl2VXgKjFB+gZzLuZzfMUxdXjew4PK8vYyjwCHq
RKREwOA28GMFiBrAfd5vEXlNv2tcRlazECxhKyVnCttv8OSMaD+GxJdwBtojDXPK
cbVGnCwGLF+MygS5zqIgenyo7HwEArFWme9KVzDom1Jr1ehuGFpaZeEDUBC2hxtx
ORVRGqvMNlhbrxKnS4AnVnk6qnEwFClnR7gdC/woX0v0fpeHVPIKfbt5eTK/ab8I
Cn/XOTG72vKnfqAUdIYgUuidiYXgu6e0FBdKyNvJC8M/hMUGmvQtnYWR0wY7KyTX
5tI9jG8bpQwkVLl93PLsmwPonGdpME3eV6Iuz7gdEWC0LKTzzIwcIWNQ1xejnyEx
wQzuLtD1r5ImrnDEYlpymaWkxNpJnw12TVyTrHKHoFrMrC2eUTZRnzmOHX+XvB/b
pCoLAgMBAAGjNTAzMB0GA1UdDgQWBBRu0no4Hdx5WtB0bpHWoYJx4IRYozASBgNV
HRMBAf8ECDAGAQH/AgEAMA0GCSqGSIb3DQEBCwUAA4ICAQBpsi+qhtKMmqbzmxjA
XwJ6667wOyQKToXzk1Qoc8k0ZmmyUNquxJa34xFuV8n6jeE2nGus3J2AEOmuYIs8
DxV35mGDOSnjFN4ozH6Q4nng2u0jfAYiDNyZW6arI8mZfcHOjbWcoAKnIzk5dz9L
Kj4AEJNGi2yLFyp2EFJusYW3d7kIf+GeM9yxxUlKjFX0G7JsOe+w1MSd1ni523sq
+klV4EWChEU+sxrv6XmsYL/mOeFirw2KHbvdprhiLj5XZ5ihMmyIrWHpP37T9NzE
ByAYbEMp/9TijcB0Jgox62GdI+o9rqwHiqI4AU9OBC/iNtz6Yt1g+7EgCyh2D1kt
TGCBQvct0BNqdVjxF+j9gYZdX/KSr/zC/ZCkb9mo0EIrGkNI7h0XBgs/WQWY9Ebg
2l8eYTzgmrtUKpOaaZ3yl1GDa2zQN3qmRUgXtqMyB6z4/MuNOwnw6OhgdNW0nDXc
2zwAEspl3NqhlMna2ggXqM01YknwrcsqwDg2k7Y4V+4j59ndR0KfNiI/fQeCSPFV
figtdHavph2XMxlMw9fT6BfoSIa9RryPzC+zlCetqGklXwf8no4FoOcD3gSv5Iv/
jWxOpUt6adoRCaNZDT86AceVzxvKY3exJ2p8vvlWJbF0R+dofFfk8FvaD3H9Gpoz
opNhzJmAq8RVCsMtB1FTDdRjAg==
-----END CERTIFICATE-----
''']